# file: docker-compose.yml

# --- ИЗМЕНЕНИЕ 1: Определяем общую сеть ---
networks:
  telegram_bot_net:
    driver: bridge

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: my_telegram_bot_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DB_NAME:-telegram_bot_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-telegram_bot_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # --- ИЗМЕНЕНИЕ 2: Подключаем сервис к нашей сети ---
    networks:
      - telegram_bot_net

  redis_db:
    image: redis:7-alpine
    container_name: my_telegram_bot_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    # --- ИЗМЕНЕНИЕ 3: Подключаем сервис к нашей сети ---
    networks:
      - telegram_bot_net

  bot:
    build: .
    container_name: my_telegram_bot_app
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && python main.py"
    # --- ИЗМЕНЕНИЕ 4: Подключаем сервис к нашей сети ---
    networks:
      - telegram_bot_net

volumes:
  postgres_data: