"""add last unban request at to user

Revision ID: 3c8d7e6f1b0a
Revises: 2b9e8e2c1a0f
Create Date: 2025-08-23 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8d7e6f1b0a'
down_revision: Union[str, None] = '2b9e8e2c1a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_unban_request_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_unban_request_at')
    # ### end Alembic commands ###