"""Add support warnings to user

Revision ID: 6b1c2d3e4f5a
Revises: 5a1b2c3d4e5f
Create Date: 2025-08-29 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c2d3e4f5a'
down_revision: Union[str, None] = '5a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('support_warnings', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('support_cooldown_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'support_cooldown_until')
    op.drop_column('users', 'support_warnings')
    # ### end Alembic commands ###