"""Add photo to support ticket

Revision ID: 7c2d3e4f5a6b
Revises: 6b1c2d3e4f5a
Create Date: 2025-08-29 14:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2d3e4f5a6b'
down_revision: Union[str, None] = '6b1c2d3e4f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('photo_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'photo_file_id')
    # ### end Alembic commands ###