"""Add reward and system settings

Revision ID: 8a9b7c6d5e4f
Revises: 7c2d3e4f5a6b
Create Date: 2025-09-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9b7c6d5e4f'
down_revision: Union[str, None] = '7c2d3e4f5a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_settings',
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('place')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('reward_settings')
    # ### end Alembic commands ###