# file: alembic/versions/9f8e7d6c5b4a_add_confirmation_screenshot_to_review.py

"""Add confirmation screenshot to Review

Revision ID: 9f8e7d6c5b4a
Revises: 8a9b7c6d5e4f
Create Date: 2025-09-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8e7d6c5b4a'
down_revision: Union[str, None] = '8a9b7c6d5e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('confirmation_screenshot_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'confirmation_screenshot_file_id')
    # ### end Alembic commands ###