"""Add details to operation history

Revision ID: a0b1c2d3e4f5
Revises: f6a7b8c9d0e1
Create Date: 2025-10-04 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b1c2d3e4f5'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_history', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('operation_history', sa.Column('media_json', sa.Text(), nullable=True))
    op.add_column('operation_history', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('operation_history', sa.Column('sender_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_history', 'sender_id')
    op.drop_column('operation_history', 'is_anonymous')
    op.drop_column('operation_history', 'media_json')
    op.drop_column('operation_history', 'comment')
    # ### end Alembic commands ###