"""add complaints and post buttons

Revision ID: e1d2c3b4a5f6
Revises: b3daea0d0b0a
Create Date: 2025-10-05 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d2c3b4a5f6'
down_revision: Union[str, None] = 'b3daea0d0b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('complainant_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', name='complaint_status_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['operation_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post_templates', sa.Column('buttons_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_templates', 'buttons_json')
    op.drop_table('transfer_complaints')
    # ### end Alembic commands ###