"""add reward gender to links

Revision ID: f1e2d3c4b5a6
Revises: b3daea0d0b0a 
Create Date: 2025-10-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e2d3c4b5a6'
down_revision: Union[str, None] = 'e1d2c3b4a5f6' # Укажите здесь ID последней существующей миграции
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('any', 'male', 'female', name='gender_enum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('links', sa.Column('reward_amount', sa.Float(), server_default=sa.text("'0.0'"), nullable=False))
    op.add_column('links', sa.Column('gender_requirement', gender_enum, server_default=sa.text("'any'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'gender_requirement')
    op.drop_column('links', 'reward_amount')
    
    gender_enum = sa.Enum('any', 'male', 'female', name='gender_enum')
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###