"""add campaign tag to links

Revision ID: g7h8i9j0k1l2
Revises: f1e2d3c4b5a6
Create Date: 2025-10-10 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g7h8i9j0k1l2'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('campaign_tag', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('stake_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'stake_amount')
    op.drop_column('links', 'campaign_tag')
    # ### end Alembic commands ###

