"""add administrators table

Revision ID: h1i2j3k4l5m6
Revises: g7b8c9d0e1f2
Create Date: 2025-09-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'h1i2j3k4l5m6'
down_revision: Union[str, None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admin_role_enum = sa.Enum('admin', 'super_admin', name='admin_role_enum')
    admin_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('administrators',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', admin_role_enum, nullable=False),
    sa.Column('is_tester', sa.Boolean(), nullable=False),
    sa.Column('is_removable', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrators')
    op.execute("DROP TYPE admin_role_enum")
    # ### end Alembic commands ###