"""add first_task_completed flag and win_streak to users

Revision ID: m9n0o1p2q3r4
Revises: g7h8i9j0k1l2
Create Date: 2025-10-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'm9n0o1p2q3r4'
# --- ИЗМЕНЕНИЕ: Указываем, что эта миграция идет ПОСЛЕ g7h8i9j0k1l2 ---
down_revision: Union[str, None] = 'g7h8i9j0k1l2'
# --------------------------------------------------------------------
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_task_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('win_streak', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'win_streak')
    op.drop_column('users', 'first_task_completed')
    # ### end Alembic commands ###