# file: alembic/versions/o3p4q5r6s7t8_add_response_time_to_internship_application.py

"""add response time to internship application

Revision ID: o3p4q5r6s7t8
Revises: n7o8p9q0r1s2
Create Date: 2025-09-27 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'o3p4q5r6s7t8'
down_revision: Union[str, None] = 'n7o8p9q0r1s2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internship_applications', sa.Column('response_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internship_applications', 'response_time')
    # ### end Alembic commands ###